language: python
python:
  - "2.7"

# command to install dependencies
install: "pip install -r requirements.txt"

# commands to run tests
before_script: 
  - mysql -e 'CREATE DATABASE development;'
  - python db_create.py

script:
  - nosetests

#after_success:
#  - codecov
env:
  - DB_USERNAME=travis
  - DB_HOST=localhost
  - DB_PORT=3306
  - DB_DBNAME=development

services:
  - mysql
