language: python
python:
  - "2.7"

# command to install dependencies
install: "pip install -r requirements.txt"

# commands to run tests
before_script:
  - export DB_USERNAME=travis
  - export DB_HOST=localhost
  - export DB_PORT=3306
  - export DB_DBNAME=development
  - mysql -e 'CREATE DATABASE development;'
  - python db_create.py

script:
  - nosetests

services:
  - mysql
