language: python
python:
  - "2.7"

# command to install dependencies
install: "pip install -r requirements.txt"

# commands to run tests
before_script: python db_create.py

script:
  - nosetests

#after_success:
#  - codecov
env:
  DATABASE_URI=mysql+pymysql://root:@127.0.0.1:3306/development
services:
  - mysql
